"""empty message

Revision ID: 3096e2810a39
Revises: eace6f0b0521
Create Date: 2022-06-22 20:23:00.261924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3096e2810a39'
down_revision = 'eace6f0b0521'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
