"""empty message

Revision ID: 6fdae73bbf96
Revises: 3096e2810a39
Create Date: 2022-06-25 10:10:24.434517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdae73bbf96'
down_revision = '3096e2810a39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_project')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_project_bill_to", 'bill_to', ['bill_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint("fk_project_bill_to", type_='foreignkey')
        batch_op.drop_column('bill_to_id')

    op.create_table('_alembic_tmp_project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('bill_to_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bill_to_id'], ['bill_to.id'], name='fk_bill_to_project'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
