"""empty message

Revision ID: 8e95e459a6fb
Revises: 6fdae73bbf96
Create Date: 2022-06-25 22:07:35.765822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e95e459a6fb'
down_revision = '6fdae73bbf96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.DATE(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('paid')
        batch_op.drop_column('sent')

    # ### end Alembic commands ###
